"""Report template generation for abuse reports."""

from datetime import datetime
from typing import Optional

from .base import ReportEvidence


class ReportTemplates:
    """Generates formatted abuse reports for various platforms."""

    @classmethod
    def generic_email(cls, evidence: ReportEvidence, reporter_email: str) -> dict:
        """
        Generate a generic abuse report email.

        Returns dict with 'subject' and 'body' keys.
        """
        subject = f"Phishing Report: {evidence.domain}"

        body = f"""ABUSE REPORT: Cryptocurrency Phishing Site
{'=' * 50}

Date: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}
Reporter: {reporter_email}
Type: Phishing / Cryptocurrency Seed Phrase Theft

REPORTED DOMAIN
---------------
Domain: {evidence.domain}
URL: {evidence.url}
Detection Confidence: {evidence.confidence_score}%
Detected At: {evidence.detected_at.isoformat()}

DETECTION REASONS
-----------------
{cls._format_list(evidence.detection_reasons)}

"""

        if evidence.suspicious_endpoints:
            body += f"""SUSPICIOUS ENDPOINTS
--------------------
{cls._format_list(evidence.suspicious_endpoints[:10])}

"""

        if evidence.backend_domains:
            body += f"""BACKEND INFRASTRUCTURE
----------------------
{cls._format_list(evidence.backend_domains)}

"""

        if evidence.api_keys_found:
            body += f"""EXPOSED API KEYS (for detection)
---------------------------------
{cls._format_list(evidence.api_keys_found)}

"""

        body += """IMPACT
------
This site impersonates a legitimate cryptocurrency wallet and attempts
to steal users' seed phrases (recovery words). Seed phrases provide
complete control over cryptocurrency wallets, enabling theft of funds
with no recourse for victims.

REQUESTED ACTION
----------------
Please investigate and take appropriate action to suspend/remove this
phishing infrastructure.

---
Report generated by SeedBuster (github.com/elldeeone/seedbuster)
"""

        return {"subject": subject, "body": body}

    @classmethod
    def digitalocean(cls, evidence: ReportEvidence, reporter_email: str) -> dict:
        """
        Generate a DigitalOcean-specific abuse report.

        Optimized for their abuse form/email format.
        """
        subject = f"Phishing Infrastructure Report: {evidence.domain}"

        body = f"""ABUSE REPORT: Cryptocurrency Seed Phrase Phishing Infrastructure
{'=' * 65}

Date: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}
Reporter: {reporter_email}
Type: Phishing / Cryptocurrency Theft

SUMMARY
-------
DigitalOcean App Platform applications are being used as backend
infrastructure for a cryptocurrency seed phrase phishing operation.

PHISHING DOMAIN
---------------
Frontend: {evidence.domain}
URL: {evidence.url}
Detection Confidence: {evidence.confidence_score}%

"""

        if evidence.backend_domains:
            body += """MALICIOUS DIGITALOCEAN APPLICATIONS
------------------------------------
"""
            for backend in evidence.backend_domains:
                if "ondigitalocean.app" in backend:
                    body += f"- {backend}\n"
            body += "\n"

        body += f"""DETECTION EVIDENCE
------------------
{cls._format_list(evidence.detection_reasons)}

"""

        if evidence.suspicious_endpoints:
            body += f"""EXFILTRATION ENDPOINTS
----------------------
{cls._format_list(evidence.suspicious_endpoints[:5])}

"""

        if evidence.api_keys_found:
            body += f"""API KEYS FOUND IN MALICIOUS CODE
---------------------------------
{cls._format_list(evidence.api_keys_found)}

"""

        body += """IMPACT
------
Cryptocurrency seed phrases provide complete control over victims' wallets.
This infrastructure enables theft of cryptocurrency funds with no recourse.

REQUESTED ACTION
----------------
Please immediately suspend/terminate the DigitalOcean App Platform
applications listed above and preserve logs for potential law enforcement.

---
Report generated by SeedBuster
"""

        return {"subject": subject, "body": body}

    @classmethod
    def cloudflare(cls, evidence: ReportEvidence, reporter_email: str) -> dict:
        """
        Generate a Cloudflare abuse report.

        Formatted for their abuse form.
        """
        subject = f"Phishing Report: {evidence.domain}"

        # Cloudflare form has specific fields, this is for the description
        body = f"""Cryptocurrency seed phrase phishing site.

Domain: {evidence.domain}
URL: {evidence.url}
Confidence: {evidence.confidence_score}%

This site impersonates a legitimate cryptocurrency wallet and steals
users' seed phrases (12/24 word recovery phrases), enabling theft of
cryptocurrency funds.

Detection reasons:
{cls._format_list(evidence.detection_reasons)}

Reporter: {reporter_email}
Detection tool: SeedBuster
"""

        return {
            "subject": subject,
            "body": body,
            "abuse_type": "phishing",
            "url": evidence.url,
        }

    @classmethod
    def registrar(
        cls,
        evidence: ReportEvidence,
        reporter_email: str,
        registrar_name: Optional[str] = None,
    ) -> dict:
        """
        Generate a domain registrar abuse report.

        For requesting domain suspension.
        """
        registrar_str = f" ({registrar_name})" if registrar_name else ""
        subject = f"Domain Abuse Report: {evidence.domain}"

        body = f"""DOMAIN ABUSE REPORT{registrar_str}
{'=' * 50}

Date: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}
Reporter: {reporter_email}

REPORTED DOMAIN
---------------
Domain: {evidence.domain}
Abuse Type: Phishing / Cryptocurrency Theft
Detection Confidence: {evidence.confidence_score}%

DESCRIPTION
-----------
This domain is being used for cryptocurrency phishing. It impersonates
a legitimate cryptocurrency wallet application and collects users' seed
phrases (12/24 word recovery phrases). These phrases provide complete
control over cryptocurrency wallets, enabling theft of funds.

EVIDENCE
--------
{cls._format_list(evidence.detection_reasons)}

"""

        if evidence.suspicious_endpoints:
            body += f"""Malicious endpoints detected:
{cls._format_list(evidence.suspicious_endpoints[:5])}

"""

        body += """REQUESTED ACTION
----------------
Please investigate and consider suspending this domain in accordance
with your acceptable use policy.

---
Report generated by SeedBuster (automated phishing detection)
"""

        return {"subject": subject, "body": body}

    @classmethod
    def phishtank_comment(cls, evidence: ReportEvidence) -> str:
        """Generate a comment for PhishTank submission."""
        lines = [
            f"Cryptocurrency seed phrase phishing site.",
            f"Confidence: {evidence.confidence_score}%",
            "",
            "Detection reasons:",
        ]
        for reason in evidence.detection_reasons[:5]:
            lines.append(f"- {reason}")

        if evidence.backend_domains:
            lines.append("")
            lines.append("Backend infrastructure:")
            for backend in evidence.backend_domains[:3]:
                lines.append(f"- {backend}")

        lines.append("")
        lines.append("Detected by SeedBuster")

        return "\n".join(lines)

    @classmethod
    def google_safebrowsing_comment(cls, evidence: ReportEvidence) -> str:
        """Generate additional info for Google Safe Browsing report."""
        lines = [
            "Cryptocurrency wallet phishing - steals seed phrases",
            "",
            "Evidence:",
        ]
        for reason in evidence.detection_reasons[:5]:
            lines.append(f"- {reason}")

        return "\n".join(lines)

    @staticmethod
    def _format_list(items: list[str], prefix: str = "- ") -> str:
        """Format a list of items with prefix."""
        if not items:
            return "(none)"
        return "\n".join(f"{prefix}{item}" for item in items)
